### ISSUE TITLE
Magicsee N5 Max X4

### ISSUE THREAD

**Issue by deleonkikko** [arthur-liberman/vfd-configurations#12]
Would it be possible to get the vfd for this box?

thank you

**Comment by arthur-liberman** [comment]
Should be doable.
Boot up Android, and in the app Terminal run the following command, and post the output.
`cat /sys/kernel/debug/gpio`

**Comment by arthur-liberman** [comment]
Yeah, in that case there's not much I can do. You'll need to reinstall Android or ask someone with a similar device to produce the needed output.

**Comment by deleonkikko** [comment]
> Necesito esta salida de Android o cualquier sistema operativo que tenga en la caja donde funciona la pantalla para averiguar qué pines está utilizando la pantalla. Otra opción es obtener el archivo DTB de Android de la caja, lo que se puede hacer desde CE. Si ya está utilizando CoreELEC, consulte el hilo VFD https://discourse.coreelec.org/t/how-to-configure-vfd/427/827?u=thecoolest

The dtb of the device is generic for the x4. In any case, if you tell me where I can find the dtb, I can send it

**Comment by arthur-liberman** [comment]
https://discourse.coreelec.org/t/extracting-dtb-file-from-a-running-android-os/1218/3

**Comment by deleonkikko** [comment]
I already have it but it won't let me send it. it gives me an error

**Comment by arthur-liberman** [comment]
You should be able to attach it on the forum or here.

**Comment by Fly-a-rgb** [comment]
Hello, could you help me generate the VFD?
I have extracted the following data from Magicsee N5 MAX X4.
Thank you
![imagen](https://github.com/arthur-liberman/vfd-configurations/assets/144459728/97ed0568-a342-4668-a045-46c63007ddcf)

**Comment by arthur-liberman** [comment]
Try this [magicsee-n5-max-x4-vfd.conf.txt](https://github.com/arthur-liberman/vfd-configurations/files/12560558/magicsee-n5-max-x4-vfd.conf.txt) (change file name to `vfd.conf`).
If it doesn't work then edit the file with
```
vfd_gpio_clk='0,36,0'
vfd_gpio_dat='0,35,0'
vfd_gpio_stb='0,0,0xFF'
```

**Comment by Fly-a-rgb** [comment]
It works correctly, thank you very much

**Comment by arthur-liberman** [comment]
Added the config to the repo - a8ffc9f13737a4af54ee46603f08a7aced875551
