### ISSUE TITLE
vfd in emuelec 4.7 is CE4

### ISSUE THREAD

**Issue by alonsocr23** [arthur-liberman/vfd-configurations#17]
I put the vfd.conf file (which used and worked in emuelec 4.5) in an HK1 Box in the path where it should be put in emuelec 4.7 but I get an error on the screen that says CE4. How can it be solved? Thank you

**Comment by arthur-liberman** [comment]
Hi,
I'm not familiar with EE,  I'd suggest posting on their forum.
